required = ["github.com/zackslash/go-bindata"]

[[constraint]]
  name = "github.com/ashwanthkumar/slack-go-webhook"
  version = "0.2.0"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.0.1"
